### ISSUE TITLE
Failed to activate the build-make package

### ISSUE THREAD

**Issue by miccio-dk** [AtomBuild/atom-build-make#22]
[Enter steps to reproduce below:]
1. Open Atom.

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [build-make](https://github.com/AtomBuild/atom-build-make) package, v0.9.0
### Stack Trace

Failed to activate the build-make package

```
At Cannot find module 'voucher'

Error: Cannot find module 'voucher'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/miccio/.atom/packages/build-make/lib/make.js:6:37)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.9.3
build, v0.60.0
build-make, v0.9.0
build-make-file, v0.1.1
build-tools, v4.5.1
file-icons, v1.7.8
linter, v1.11.4
linter-gcc, v0.6.13
platformio-ide, v1.2.0
platformio-ide-terminal, v2.0.9
terminal-plus, v0.14.5
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
Please re-install the package. This can happen sometimes if there are e.g. connection issues or problem with npm registry when installing a package.

**Comment by miccio-dk** [comment]
Hi noseglid,

and thanks for the hint.
Unfortunately, reinstalling the package yielded the same error. 

```
apm remove build-make
apm install build-make
```

I had to install voucher manually through npm:

```
npm install voucher
```

Is this the desired behaviur?

**Comment by noseglid** [comment]
Nope definitely not.

It is specified as a dependency: https://github.com/AtomBuild/atom-build-make/blob/master/package.json#L35

APM is responsible of installing deps. I'd suggest you post an issue there if you have a reliable way of reproducing!

**Comment by miccio-dk** [comment]
I could try performing it in a virtual machine. Maybe it's a specific issue with the new Ubuntu 16.04.
Is there a way of getting a more verbose output from APM in order to detect the issue? :)

**Comment by noseglid** [comment]
I don't have much in depth knowledge of `apm` unfortunately. you'd have to turn to that project.
